create table demo_phone (
   phone_id bigint generated by default as identity,
    city_code varchar(255),
    country_code varchar(255),
    number varchar(255),
    user_user_id bigint,
    primary key (phone_id)
);

create table demo_user (
   user_id bigint generated by default as identity,
    created timestamp,
    email varchar(255),
    isactive boolean,
    last_login timestamp,
    modified timestamp,
    token varchar(255),
    user_name varchar(255),
    user_password varchar(255),
    primary key (user_id)
);

alter table demo_phone
   add constraint FK_user_user_id
   foreign key (user_user_id)
   references demo_user;